### ISSUE TITLE
Contact source

### ISSUE THREAD

**Issue by masetto** [twomice/com.joineryhq.textselect#7]
@twomice, very useful extension.
Is there a reason why the Select for contact source is not provided?

**Comment by twomice** [comment]
@masetto Only because no one did it yet. I'm certainly open to a PR for it. If you want to try it, you could probably borrow pretty easily from the code that does this for Contribution Source. If you have success, a PR would be most welcome!

**Comment by masetto** [comment]
@twomice I opened a [PR](https://github.com/twomice/com.joineryhq.textselect/pull/8). Can you see if it's OK?
