### ISSUE TITLE
Support for contribution source in contribution profile pages.

### ISSUE THREAD

**Issue by masetto** [twomice/com.joineryhq.textselect#9]
In `js/textselect.js` (https://github.com/twomice/com.joineryhq.textselect/blob/431ee11a7bf3ff15d437311e9bd27daef0fe8190/js/textselect.js#L42) I try to add this lines to support contribution source in profile pages:

```

    if (jqEl.length == 0 && fieldIds[i] == 'contribution_source') {
      jqEl = CRM.$('input#' + fieldIds[i]);
    }

```

Is it intentional that now it is not supported in contribution profile pages?

**Comment by twomice** [comment]
@masetto Thanks for the report. Contribution Source field has varying attributes, depending on the form (back-end "add/edit contribution" vs profile). This should be fixed, as of https://github.com/twomice/com.joineryhq.textselect/commit/39639d0c6b153c0e977b0ce209ba254452407398. Please try the latest master and re-open this ticket if you find it's not working for you.

**Comment by masetto** [comment]
@twomice It's OK for me. Thank you.
